# Hydra runtime configuration
run:
  dir: outputs/${name}/${condition}/seed_${seed}/${now:%Y-%m-%d_%H-%M-%S}

sweep:
  dir: outputs/${name}/sweeps/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.override_dirname}

job:
  chdir: false
